# 데이터를 보기 좋게 출력하기 위한 문자열 처리 함수
def char_replace(meal) :
	meal = meal.translate({ ord('['): '', ord(']'): '', ord('{'): '', ord('}'): '', ord("'"): '', ord(','): '\n', ord(':'): '\n',ord(' '): ''})
	meal = meal.replace('\n', '\n·')
	meal = meal.replace('-중식/석식-', '\n[중식/석식]')
	meal = meal.replace('-조식-', '[조식]')
	meal = meal.replace('-컵밥-', '컵밥]')
	meal = meal.replace('-중식-', '\n[중식]')
	meal = meal.replace('-석식-', '\n[석식]')
	meal = meal.replace('-한식-', '\n[한식]')
	meal = meal.replace('-덮밥-', '\n[덮밥]')
	meal = meal.replace('-양식-', '\n[양식]')
	meal = meal.replace('-도시락-', '\n[도시락]')
	meal = meal.replace('-스페셜메뉴-', '\n[스페셜메뉴]')
	meal = meal.replace('-돈까스-', '\n[돈까스]')
	meal = meal.replace('-라면-', '\n[라면]')
	meal = meal.replace('-메뉴-', '\n[메뉴]')
	meal = meal.replace('-부대라면-', '\n[부대라면]')
	meal = meal.replace('-한정메뉴-', '\n[한정메뉴]')
	meal = meal.replace('-샐러드바-', '\n[샐러드바]')
	meal = meal.replace('\n·\n', '\n\n')
	return meal
